/* ==========  user  ========== */
export const USER_LOGIN_BEGIN = 'USER_LOGIN_BEGIN'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_ERROR = 'USER_LOGIN_ERROR'

export const USER_LOGOUT = 'USER_LOGOUT'
export const USER_REGISTER_BEGIN = 'USER_REGISTER_BEGIN'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_ERROR = 'USER_REGISTER_ERROR'

/* ==========  article  ==========  */
export const ARTICLE_GET_ARTICLELIST_BEGIN = 'ARTICLE_GET_ARTICLELIST_BEGIN'
export const ARTICLE_GET_ARTICLELIST_SUCCESS = 'ARTICLE_GET_ARTICLELIST_SUCCESS'
export const ARTICLE_GET_ARTICLELIST_ERROR = 'ARTICLE_GET_ARTICLELIST_ERROR'
